version: "3"

services:
    web:
        image: easter/web
        container_name: easter-web
        tty: true
        build:
          context: ./web
          dockerfile: dockerfile
        ports:
          - "3000:3000"
        networks:
          - easter-net
        volumes:
          - ./ops:/easter/ops
          - ./web:/easter/web
        env_file:
          - ./ops/dev.env

networks:
    easter-net:
        driver: bridge