FROM        node:12

ARG         API_PORT

# The base node image sets a very verbose log level.
ENV         NPM_CONFIG_LOGLEVEL warn

RUN         apt-get update \
    && apt-get install zip python3-dev python3-pip -y
RUN         pip3 install --upgrade --user awscli awsebcli==3.10
RUN         echo 'export PATH=~/.local/bin:$PATH' >> ~/.bashrc
RUN         npm install -g nodemon serverless npm

RUN         mkdir -p /easter/api
RUN         mkdir -p /easter/aws/dynamo-db
WORKDIR     /easter/api

ENV         API_PORT ${API_PORT}
ENV         OPS_PORT ${OPS_PORT}
EXPOSE      ${API_PORT}
EXPOSE      ${OPS_PORT}
EXPOSE      8000

ENTRYPOINT  ["sleep", "2d"]